const standingsData = [
    {
        rank: 1,
        club: "Manchester City",
        matchPlayed: 38,
        win: 29,
        draw: 6,
        lost: 3,
        goalsFor: 99,
        goalsAgainst: 26,
        goalsDiff: 73,
        point: 93,
    },
    {
        rank: 2,
        club: "Liverpool",
        matchPlayed: 38,
        win: 28,
        draw: 8,
        lost: 2,
        goalsFor: 94,
        goalsAgainst: 26,
        goalsDiff: 68,
        point: 92,
    },
    {
        rank: 3,
        club: "Chelsea",
        matchPlayed: 38,
        win: 21,
        draw: 11,
        lost: 6,
        goalsFor: 76,
        goalsAgainst: 33,
        goalsDiff: 43,
        point: 74,
    },
    {
        rank: 4,
        club: "Tottenham Hospur",
        matchPlayed: 38,
        win: 22,
        draw: 5,
        lost: 11,
        goalsFor: 69,
        goalsAgainst: 40,
        goalsDiff: 29,
        point: 71,
    },
    {
        rank: 5,
        club: "Arsenal",
        matchPlayed: 38,
        win: 22,
        draw: 3,
        lost: 13,
        goalsFor: 61,
        goalsAgainst: 48,
        goalsDiff: 13,
        point: 69,
    },
    {
        rank: 6,
        club: "Manchester United",
        matchPlayed: 38,
        win: 16,
        draw: 10,
        lost: 12,
        goalsFor: 57,
        goalsAgainst: 57,
        goalsDiff: 0,
        point: 58,
    },
    {
        rank: 7,
        club: "West Ham United",
        matchPlayed: 38,
        win: 16,
        draw: 8,
        lost: 14,
        goalsFor: 60,
        goalsAgainst: 51,
        goalsDiff: 9,
        point: 56,
    },
    {
        rank: 8,
        club: "Leicester City",
        matchPlayed: 38,
        win: 14,
        draw: 10,
        lost: 14,
        goalsFor: 62,
        goalsAgainst: 59,
        goalsDiff: 3,
        point: 52,
    },
    {
        rank: 9,
        club: "Brighton and Hove Albion",
        matchPlayed: 38,
        win: 12,
        draw: 15,
        lost: 11,
        goalsFor: 42,
        goalsAgainst: 44,
        goalsDiff: -2,
        point: 51,
    },
    {
        rank: 10,
        club: "Wolverhampton",
        matchPlayed: 38,
        win: 15,
        draw: 6,
        lost: 17,
        goalsFor: 38,
        goalsAgainst: 43,
        goalsDiff: -5,
        point: 51,
    },
    {
        rank: 11,
        club: "Newcastle United",
        matchPlayed: 38,
        win: 13,
        draw: 10,
        lost: 15,
        goalsFor: 44,
        goalsAgainst: 62,
        goalsDiff: -18,
        point: 49,
    },
    {
        rank: 12,
        club: "Crystal Palace",
        matchPlayed: 38,
        win: 11,
        draw: 15,
        lost: 12,
        goalsFor: 50,
        goalsAgainst: 46,
        goalsDiff: 4,
        point: 48,
    },
    {
        rank: 13,
        club: "Brentford",
        matchPlayed: 38,
        win: 13,
        draw: 7,
        lost: 18,
        goalsFor: 48,
        goalsAgainst: 56,
        goalsDiff: -8,
        point: 46,
    },
    {
        rank: 14,
        club: "Aston Villa",
        matchPlayed: 38,
        win: 13,
        draw: 6,
        lost: 19,
        goalsFor: 52,
        goalsAgainst: 54,
        goalsDiff: -2,
        point: 45,
    },
    {
        rank: 15,
        club: "Southampton",
        matchPlayed: 38,
        win: 9,
        draw: 13,
        lost: 16,
        goalsFor: 43,
        goalsAgainst: 67,
        goalsDiff: -24,
        point: 40,
    },
    {
        rank: 16,
        club: "Everton",
        matchPlayed: 38,
        win: 11,
        draw: 6,
        lost: 21,
        goalsFor: 43,
        goalsAgainst: 66,
        goalsDiff: -23,
        point: 39,
    },
    {
        rank: 17,
        club: "Leeds United",
        matchPlayed: 38,
        win: 9,
        draw: 11,
        lost: 18,
        goalsFor: 42,
        goalsAgainst: 79,
        goalsDiff: -37,
        point: 38,
    },
    {
        rank: 18,
        club: "Burnley",
        matchPlayed: 38,
        win: 7,
        draw: 14,
        lost: 17,
        goalsFor: 34,
        goalsAgainst: 53,
        goalsDiff: -19,
        point: 35,
    },
    {
        rank: 19,
        club: "Watford",
        matchPlayed: 38,
        win: 6,
        draw: 5,
        lost: 27,
        goalsFor: 34,
        goalsAgainst: 77,
        goalsDiff: -43,
        point: 23,
    },
    {
        rank: 20,
        club: "Norwich City",
        matchPlayed: 38,
        win: 5,
        draw: 7,
        lost: 26,
        goalsFor: 23,
        goalsAgainst: 84,
        goalsDiff: -61,
        point: 22,
    },
];

export const getStandingsPost = () => {
    var posts = standingsData;
    var myPromise = new Promise((resolve, reject) => {
        resolve(posts);
    });
    return myPromise;
};
