const standingsData = [
    {
        rank: 1,
        club: "Paris Saint-Germain",
        matchPlayed: 38,
        win: 26,
        draw: 8,
        lost: 4,
        goalsFor: 90,
        goalsAgainst: 36,
        goalsDiff: 54,
        point: 86,
    },
    {
        rank: 2,
        club: "Marseille",
        matchPlayed: 38,
        win: 21,
        draw: 8,
        lost: 9,
        goalsFor: 63,
        goalsAgainst: 38,
        goalsDiff: 25,
        point: 71,
    },
    {
        rank: 3,
        club: "AS Monaco",
        matchPlayed: 38,
        win: 20,
        draw: 9,
        lost: 9,
        goalsFor: 65,
        goalsAgainst: 40,
        goalsDiff: 25,
        point: 69,
    },
    {
        rank: 4,
        club: "Rennes",
        matchPlayed: 38,
        win: 20,
        draw: 6,
        lost: 12,
        goalsFor: 82,
        goalsAgainst: 40,
        goalsDiff: 42,
        point: 66,
    },
    {
        rank: 5,
        club: "Nice",
        matchPlayed: 38,
        win: 20,
        draw: 7,
        lost: 11,
        goalsFor: 52,
        goalsAgainst: 36,
        goalsDiff: 16,
        point: 66,
    },
    {
        rank: 6,
        club: "Strasbourg",
        matchPlayed: 38,
        win: 17,
        draw: 12,
        lost: 9,
        goalsFor: 60,
        goalsAgainst: 43,
        goalsDiff: 17,
        point: 63,
    },
    {
        rank: 7,
        club: "Lens",
        matchPlayed: 38,
        win: 17,
        draw: 11,
        lost: 10,
        goalsFor: 62,
        goalsAgainst: 48,
        goalsDiff: 14,
        point: 62,
    },
    {
        rank: 8,
        club: "Lyon",
        matchPlayed: 38,
        win: 17,
        draw: 11,
        lost: 10,
        goalsFor: 66,
        goalsAgainst: 51,
        goalsDiff: 15,
        point: 61,
    },
    {
        rank: 9,
        club: "Nantes",
        matchPlayed: 38,
        win: 15,
        draw: 10,
        lost: 13,
        goalsFor: 55,
        goalsAgainst: 48,
        goalsDiff: 7,
        point: 55,
    },
    {
        rank: 10,
        club: "LOSC Lille",
        matchPlayed: 38,
        win: 14,
        draw: 13,
        lost: 11,
        goalsFor: 48,
        goalsAgainst: 48,
        goalsDiff: 0,
        point: 55,
    },
    {
        rank: 11,
        club: "Brest",
        matchPlayed: 38,
        win: 13,
        draw: 9,
        lost: 16,
        goalsFor: 49,
        goalsAgainst: 6257,
        goalsDiff: -8,
        point: 48,
    },
    {
        rank: 12,
        club: "Stade de Reims",
        matchPlayed: 38,
        win: 11,
        draw: 13,
        lost: 14,
        goalsFor: 43,
        goalsAgainst: 44,
        goalsDiff: -1,
        point: 46,
    },
    {
        rank: 13,
        club: "Montpellier",
        matchPlayed: 38,
        win: 12,
        draw: 7,
        lost: 19,
        goalsFor: 49,
        goalsAgainst: 61,
        goalsDiff: -12,
        point: 43,
    },
    {
        rank: 14,
        club: "Angers",
        matchPlayed: 38,
        win: 10,
        draw: 11,
        lost: 17,
        goalsFor: 44,
        goalsAgainst: 55,
        goalsDiff: -11,
        point: 41,
    },
    {
        rank: 15,
        club: "Troyes",
        matchPlayed: 38,
        win: 9,
        draw: 11,
        lost: 18,
        goalsFor: 37,
        goalsAgainst: 53,
        goalsDiff: -16,
        point: 38,
    },
    {
        rank: 16,
        club: "Lorient",
        matchPlayed: 38,
        win: 8,
        draw: 12,
        lost: 18,
        goalsFor: 35,
        goalsAgainst: 63,
        goalsDiff: -28,
        point: 36,
    },
    {
        rank: 17,
        club: "Clermont Foot",
        matchPlayed: 38,
        win: 9,
        draw: 9,
        lost: 20,
        goalsFor: 38,
        goalsAgainst: 69,
        goalsDiff: -31,
        point: 36,
    },
    {
        rank: 18,
        club: "Saint-Etienne",
        matchPlayed: 38,
        win: 7,
        draw: 11,
        lost: 20,
        goalsFor: 42,
        goalsAgainst: 77,
        goalsDiff: -35,
        point: 32,
    },
    {
        rank: 19,
        club: "Metz",
        matchPlayed: 38,
        win: 6,
        draw: 13,
        lost: 19,
        goalsFor: 35,
        goalsAgainst: 69,
        goalsDiff: -34,
        point: 31,
    },
    {
        rank: 20,
        club: "Bordeaux",
        matchPlayed: 38,
        win: 6,
        draw: 13,
        lost: 19,
        goalsFor: 52,
        goalsAgainst: 91,
        goalsDiff: -39,
        point: 31,
    },
];

export const getStandingsPost = () => {
    var posts = standingsData;
    var myPromise = new Promise((resolve, reject) => {
        resolve(posts);
    });
    return myPromise;
};
