const data = [
    {
        matchID: 1,
        league: "English Premier League",
        host: "Manchester City",
        guest: "Aston Villa",
        result: "3-2",
    },
    {
        matchID: 2,
        league: "English Premier League",
        host: "Arsenal",
        guest: "Everton",
        result: "5-1",
    },
    {
        matchID: 3,
        league: "English Premier League",
        host: "Brentford",
        guest: "Leeds United",
        result: "1-2",
    },
    {
        matchID: 4,
        league: "English Premier League",
        host: "Brighton",
        guest: "West Ham United",
        result: "3-1",
    },
    {
        matchID: 5,
        league: "English Premier League",
        host: "Burnley",
        guest: "Newcastle United",
        result: "1-2",
    },
    {
        matchID: 6,
        league: "English Premier League",
        host: "Chelsea",
        guest: "Watford",
        result: "2-1",
    },
    {
        matchID: 7,
        league: "English Premier League",
        host: "Crystal Palace",
        guest: "Manchester United",
        result: "1-0",
    },
    {
        matchID: 8,
        league: "English Premier League",
        host: "Leicester City",
        guest: "Southampton",
        result: "4-1",
    },
    {
        matchID: 9,
        league: "English Premier League",
        host: "Liverpool",
        guest: "Wolverhampton Wanderers",
        result: "3-1",
    },
    {
        matchID: 10,
        league: "English Premier League",
        host: "Norwich City",
        guest: "Tottenham Hospur",
        result: "0-5",
    },
    {
        matchID: 11,
        league: "La Liga Santanders",
        host: "Real Madrid",
        guest: "Real Betis",
        result: "0-0",
    },
    {
        matchID: 12,
        league: "La Liga Santanders",
        host: "Rayo Vallecano",
        guest: "Levante UD",
        result: "2-4",
    },
    {
        matchID: 13,
        league: "La Liga Santanders",
        host: "Valencia",
        guest: "Celta Vigo",
        result: "2-0",
    },
    {
        matchID: 14,
        league: "La Liga Santanders",
        host: "Elche",
        guest: "Getafe",
        result: "3-1",
    },
    {
        matchID: 15,
        league: "La Liga Santanders",
        host: "Granada",
        guest: "Espanyol",
        result: "0-0",
    },
    {
        matchID: 16,
        league: "La Liga Santanders",
        host: "CA Osasuna",
        guest: "Mallorca",
        result: "0-2",
    },
    {
        matchID: 17,
        league: "La Liga Santanders",
        host: "Alaves",
        guest: "Cadiz",
        result: "0-1",
    },
    {
        matchID: 18,
        league: "La Liga Santanders",
        host: "Sevilla",
        guest: "Atletic Bilbao",
        result: "1-0",
    },
    {
        matchID: 19,
        league: "La Liga Santanders",
        host: "Real Sociedad",
        guest: "Atletico Madrid",
        result: "1-2",
    },
    {
        matchID: 20,
        league: "La Liga Santanders",
        host: "Barcelona",
        guest: "Villareal",
        result: "0-2",
    },
    {
        matchID: 21,
        league: "Serie A",
        host: "Torino",
        guest: "AS Roma",
        result: "0-3",
    },
    {
        matchID: 22,
        league: "Serie A",
        host: "Genoa",
        guest: "Bologna",
        result: "0-1",
    },
    {
        matchID: 23,
        league: "Serie A",
        host: "Fiorentina",
        guest: "Juventus",
        result: "2-0",
    },
    {
        matchID: 24,
        league: "Serie A",
        host: "Atalanta",
        guest: "Empoli",
        result: "0-1",
    },
    {
        matchID: 25,
        league: "Serie A",
        host: "Lazio",
        guest: "Hellas Verona",
        result: "3-3",
    },
    {
        matchID: 26,
        league: "Serie A",
        host: "Spezia",
        guest: "Napoli",
        result: "0-3",
    },
    {
        matchID: 27,
        league: "Serie A",
        host: "Inter Milan",
        guest: "Sampdoria",
        result: "3-0",
    },
    {
        matchID: 28,
        league: "Serie A",
        host: "Sassuolo",
        guest: "AC Milan",
        result: "0-3",
    },
    {
        matchID: 29,
        league: "Serie A",
        host: "Venezia",
        guest: "Cagliari",
        result: "0-0",
    },
    {
        matchID: 30,
        league: "Serie A",
        host: "Salernitana",
        guest: "Udinese",
        result: "0-4",
    },
    {
        matchID: 31,
        league: "Bundesliga",
        host: "Wolfsburg",
        guest: "Bayern Munich",
        result: "2-2",
    },
    {
        matchID: 32,
        league: "Bundesliga",
        host: "Arminia",
        guest: "RB Leipzig",
        result: "1-1",
    },
    {
        matchID: 33,
        league: "Bundesliga",
        host: "Mainz 05",
        guest: "Eintracht Frankfurt",
        result: "2-2",
    },
    {
        matchID: 34,
        league: "Bundesliga",
        host: "Bayer Leverkusen",
        guest: "Freiburg",
        result: "2-1",
    },
    {
        matchID: 35,
        league: "Bundesliga",
        host: "Monchengladbach",
        guest: "Hoffenheim",
        result: "5-1",
    },
    {
        matchID: 36,
        league: "Bundesliga",
        host: "Borussia Dortmund",
        guest: "Hertha Berlin",
        result: "2-1",
    },
    {
        matchID: 37,
        league: "Bundesliga",
        host: "Stuttgart",
        guest: "Koln",
        result: "2-1",
    },
    {
        matchID: 38,
        league: "Bundesliga",
        host: "Union Berlin",
        guest: "Bochum",
        result: "3-2",
    },
    {
        matchID: 39,
        league: "Bundesliga",
        host: "Augsburg",
        guest: "Greuther Furth",
        result: "2-1",
    },
    {
        matchID: 40,
        league: "Ligue 1",
        host: "Angers",
        guest: "Montpellier",
        result: "2-0",
    },
    {
        matchID: 41,
        league: "Ligue 1",
        host: "Brest",
        guest: "Bordeaux",
        result: "2-4",
    },
    {
        matchID: 42,
        league: "Ligue 1",
        host: "Clermont Foot",
        guest: "Olympique Lyon",
        result: "1-2",
    },
    {
        matchID: 43,
        league: "Ligue 1",
        host: "Lens",
        guest: "AS Monaco",
        result: "2-2",
    },
    {
        matchID: 44,
        league: "Ligue 1",
        host: "LOSC Lille",
        guest: "Rennes",
        result: "2-2",
    },
    {
        matchID: 45,
        league: "Ligue 1",
        host: "Lorient",
        guest: "Troyes",
        result: "1-1",
    },
    {
        matchID: 46,
        league: "Ligue 1",
        host: "Olympique Marseille",
        guest: "Strasbourg",
        result: "4-0",
    },
    {
        matchID: 47,
        league: "Ligue 1",
        host: "Nantes",
        guest: "AS Saint-Etienne",
        result: "1-1",
    },
    {
        matchID: 48,
        league: "Ligue 1",
        host: "Paris Saint-Germain",
        guest: "Metz",
        result: "5-0",
    },
    {
        matchID: 49,
        league: "Ligue 1",
        host: "Stade de Reims",
        guest: "OGC Nice",
        result: "2-3",
    },
];

export const getResultPost = () => {
    var posts = data;
    var myPromise = new Promise((resolve, reject) => {
        resolve(posts);
    });
    return myPromise;
};
