const standingsData = [
    {
        rank: 1,
        club: "AC Milan",
        matchPlayed: 38,
        win: 26,
        draw: 8,
        lost: 4,
        goalsFor: 69,
        goalsAgainst: 31,
        goalsDiff: 38,
        point: 86,
    },
    {
        rank: 2,
        club: "Inter Milan",
        matchPlayed: 38,
        win: 25,
        draw: 9,
        lost: 4,
        goalsFor: 84,
        goalsAgainst: 32,
        goalsDiff: 52,
        point: 84,
    },
    {
        rank: 3,
        club: "Napoli",
        matchPlayed: 38,
        win: 24,
        draw: 7,
        lost: 7,
        goalsFor: 74,
        goalsAgainst: 31,
        goalsDiff: 43,
        point: 79,
    },
    {
        rank: 4,
        club: "Juventus",
        matchPlayed: 38,
        win: 20,
        draw: 10,
        lost: 8,
        goalsFor: 57,
        goalsAgainst: 37,
        goalsDiff: 20,
        point: 70,
    },
    {
        rank: 5,
        club: "Lazio",
        matchPlayed: 38,
        win: 18,
        draw: 10,
        lost: 10,
        goalsFor: 77,
        goalsAgainst: 58,
        goalsDiff: 19,
        point: 64,
    },
    {
        rank: 6,
        club: "AS Roma",
        matchPlayed: 38,
        win: 18,
        draw: 9,
        lost: 11,
        goalsFor: 59,
        goalsAgainst: 43,
        goalsDiff: 16,
        point: 63,
    },
    {
        rank: 7,
        club: "Fiorentina",
        matchPlayed: 38,
        win: 19,
        draw: 5,
        lost: 14,
        goalsFor: 59,
        goalsAgainst: 51,
        goalsDiff: 8,
        point: 62,
    },
    {
        rank: 8,
        club: "Atalanta",
        matchPlayed: 38,
        win: 16,
        draw: 11,
        lost: 11,
        goalsFor: 65,
        goalsAgainst: 48,
        goalsDiff: 17,
        point: 59,
    },
    {
        rank: 9,
        club: "Verona",
        matchPlayed: 38,
        win: 14,
        draw: 11,
        lost: 13,
        goalsFor: 65,
        goalsAgainst: 59,
        goalsDiff: 6,
        point: 53,
    },
    {
        rank: 10,
        club: "Torino",
        matchPlayed: 38,
        win: 13,
        draw: 11,
        lost: 14,
        goalsFor: 46,
        goalsAgainst: 41,
        goalsDiff: 5,
        point: 50,
    },
    {
        rank: 11,
        club: "Sassuolo",
        matchPlayed: 38,
        win: 13,
        draw: 11,
        lost: 14,
        goalsFor: 66,
        goalsAgainst: 64,
        goalsDiff: -2,
        point: 50,
    },
    {
        rank: 12,
        club: "Udinese",
        matchPlayed: 38,
        win: 11,
        draw: 14,
        lost: 13,
        goalsFor: 61,
        goalsAgainst: 58,
        goalsDiff: 3,
        point: 47,
    },
    {
        rank: 13,
        club: "Bologna",
        matchPlayed: 38,
        win: 12,
        draw: 10,
        lost: 16,
        goalsFor: 44,
        goalsAgainst: 55,
        goalsDiff: -11,
        point: 46,
    },
    {
        rank: 14,
        club: "Empoli",
        matchPlayed: 38,
        win: 10,
        draw: 11,
        lost: 17,
        goalsFor: 50,
        goalsAgainst: 70,
        goalsDiff: -20,
        point: 41,
    },
    {
        rank: 15,
        club: "Sampdoria",
        matchPlayed: 38,
        win: 10,
        draw: 6,
        lost: 22,
        goalsFor: 46,
        goalsAgainst: 63,
        goalsDiff: -17,
        point: 36,
    },
    {
        rank: 16,
        club: "Spezia",
        matchPlayed: 38,
        win: 10,
        draw: 6,
        lost: 22,
        goalsFor: 41,
        goalsAgainst: 71,
        goalsDiff: -30,
        point: 36,
    },
    {
        rank: 17,
        club: "Salernitana",
        matchPlayed: 38,
        win: 7,
        draw: 10,
        lost: 21,
        goalsFor: 33,
        goalsAgainst: 78,
        goalsDiff: -45,
        point: 31,
    },
    {
        rank: 18,
        club: "Cagliari",
        matchPlayed: 38,
        win: 6,
        draw: 12,
        lost: 20,
        goalsFor: 34,
        goalsAgainst: 68,
        goalsDiff: -34,
        point: 30,
    },
    {
        rank: 19,
        club: "Genoa",
        matchPlayed: 38,
        win: 4,
        draw: 16,
        lost: 18,
        goalsFor: 27,
        goalsAgainst: 60,
        goalsDiff: -33,
        point: 28,
    },
    {
        rank: 20,
        club: "Venezia",
        matchPlayed: 38,
        win: 6,
        draw: 9,
        lost: 23,
        goalsFor: 34,
        goalsAgainst: 69,
        goalsDiff: -35,
        point: 27,
    },
];

export const getStandingsPost = () => {
    var posts = standingsData;
    var myPromise = new Promise((resolve, reject) => {
        resolve(posts);
    });
    return myPromise;
};
