const standingsData = [
    {
        league: "English Premier League",
        rank: 1,
        club: "Manchester City",
        matchPlayed: 38,
        win: 29,
        draw: 6,
        lost: 3,
        goalsFor: 99,
        goalsAgainst: 26,
        goalsDiff: 73,
        point: 93,
    },
    {
        league: "English Premier League",
        rank: 2,
        club: "Liverpool",
        matchPlayed: 38,
        win: 28,
        draw: 8,
        lost: 2,
        goalsFor: 94,
        goalsAgainst: 26,
        goalsDiff: 68,
        point: 92,
    },
    {
        league: "English Premier League",
        rank: 3,
        club: "Chelsea",
        matchPlayed: 38,
        win: 21,
        draw: 11,
        lost: 6,
        goalsFor: 76,
        goalsAgainst: 33,
        goalsDiff: 43,
        point: 74,
    },
    {
        league: "English Premier League",
        rank: 4,
        club: "Tottenham Hospur",
        matchPlayed: 38,
        win: 22,
        draw: 5,
        lost: 11,
        goalsFor: 69,
        goalsAgainst: 40,
        goalsDiff: 29,
        point: 71,
    },
    {
        league: "English Premier League",
        rank: 5,
        club: "Arsenal",
        matchPlayed: 38,
        win: 22,
        draw: 3,
        lost: 13,
        goalsFor: 61,
        goalsAgainst: 48,
        goalsDiff: 13,
        point: 69,
    },
    {
        league: "English Premier League",
        rank: 6,
        club: "Manchester United",
        matchPlayed: 38,
        win: 16,
        draw: 10,
        lost: 12,
        goalsFor: 57,
        goalsAgainst: 57,
        goalsDiff: 0,
        point: 58,
    },
    {
        league: "English Premier League",
        rank: 7,
        club: "West Ham United",
        matchPlayed: 38,
        win: 16,
        draw: 8,
        lost: 14,
        goalsFor: 60,
        goalsAgainst: 51,
        goalsDiff: 9,
        point: 56,
    },
    {
        league: "English Premier League",
        rank: 8,
        club: "Leicester City",
        matchPlayed: 38,
        win: 14,
        draw: 10,
        lost: 14,
        goalsFor: 62,
        goalsAgainst: 59,
        goalsDiff: 3,
        point: 52,
    },
    {
        league: "English Premier League",
        rank: 9,
        club: "Brighton and Hove Albion",
        matchPlayed: 38,
        win: 12,
        draw: 15,
        lost: 11,
        goalsFor: 42,
        goalsAgainst: 44,
        goalsDiff: -2,
        point: 51,
    },
    {
        league: "English Premier League",
        rank: 10,
        club: "Wolverhampton",
        matchPlayed: 38,
        win: 15,
        draw: 6,
        lost: 17,
        goalsFor: 38,
        goalsAgainst: 43,
        goalsDiff: -5,
        point: 51,
    },
    {
        league: "English Premier League",
        rank: 11,
        club: "Newcastle United",
        matchPlayed: 38,
        win: 13,
        draw: 10,
        lost: 15,
        goalsFor: 44,
        goalsAgainst: 62,
        goalsDiff: -18,
        point: 49,
    },
    {
        league: "English Premier League",
        rank: 12,
        club: "Crystal Palace",
        matchPlayed: 38,
        win: 11,
        draw: 15,
        lost: 12,
        goalsFor: 50,
        goalsAgainst: 46,
        goalsDiff: 4,
        point: 48,
    },
    {
        league: "English Premier League",
        rank: 13,
        club: "Brentford",
        matchPlayed: 38,
        win: 13,
        draw: 7,
        lost: 18,
        goalsFor: 48,
        goalsAgainst: 56,
        goalsDiff: -8,
        point: 46,
    },
    {
        league: "English Premier League",
        rank: 14,
        club: "Aston Villa",
        matchPlayed: 38,
        win: 13,
        draw: 6,
        lost: 19,
        goalsFor: 52,
        goalsAgainst: 54,
        goalsDiff: -2,
        point: 45,
    },
    {
        league: "English Premier League",
        rank: 15,
        club: "Southampton",
        matchPlayed: 38,
        win: 9,
        draw: 13,
        lost: 16,
        goalsFor: 43,
        goalsAgainst: 67,
        goalsDiff: -24,
        point: 40,
    },
    {
        league: "English Premier League",
        rank: 16,
        club: "Everton",
        matchPlayed: 38,
        win: 11,
        draw: 6,
        lost: 21,
        goalsFor: 43,
        goalsAgainst: 66,
        goalsDiff: -23,
        point: 39,
    },
    {
        league: "English Premier League",
        rank: 17,
        club: "Leeds United",
        matchPlayed: 38,
        win: 9,
        draw: 11,
        lost: 18,
        goalsFor: 42,
        goalsAgainst: 79,
        goalsDiff: -37,
        point: 38,
    },
    {
        league: "English Premier League",
        rank: 18,
        club: "Burnley",
        matchPlayed: 38,
        win: 7,
        draw: 14,
        lost: 17,
        goalsFor: 34,
        goalsAgainst: 53,
        goalsDiff: -19,
        point: 35,
    },
    {
        league: "English Premier League",
        rank: 19,
        club: "Watford",
        matchPlayed: 38,
        win: 6,
        draw: 5,
        lost: 27,
        goalsFor: 34,
        goalsAgainst: 77,
        goalsDiff: -43,
        point: 23,
    },
    {
        league: "English Premier League",
        rank: 20,
        club: "Norwich City",
        matchPlayed: 38,
        win: 5,
        draw: 7,
        lost: 26,
        goalsFor: 23,
        goalsAgainst: 84,
        goalsDiff: -61,
        point: 22,
    },
    {
        league: "La Liga Santanders",
        rank: 1,
        club: "Real Madrid",
        matchPlayed: 38,
        win: 26,
        draw: 8,
        lost: 4,
        goalsFor: 80,
        goalsAgainst: 31,
        goalsDiff: 49,
        point: 86,
    },
    {
        league: "La Liga Santanders",
        rank: 2,
        club: "Barcelona",
        matchPlayed: 38,
        win: 21,
        draw: 10,
        lost: 7,
        goalsFor: 68,
        goalsAgainst: 38,
        goalsDiff: 30,
        point: 73,
    },
    {
        league: "La Liga Santanders",
        rank: 3,
        club: "Atletico Madrid",
        matchPlayed: 38,
        win: 21,
        draw: 8,
        lost: 9,
        goalsFor: 65,
        goalsAgainst: 43,
        goalsDiff: 22,
        point: 71,
    },
    {
        league: "La Liga Santanders",
        rank: 4,
        club: "Sevilla",
        matchPlayed: 38,
        win: 18,
        draw: 16,
        lost: 4,
        goalsFor: 53,
        goalsAgainst: 30,
        goalsDiff: 23,
        point: 70,
    },
    {
        league: "La Liga Santanders",
        rank: 5,
        club: "Real Betis",
        matchPlayed: 38,
        win: 19,
        draw: 8,
        lost: 11,
        goalsFor: 62,
        goalsAgainst: 40,
        goalsDiff: 22,
        point: 65,
    },
    {
        league: "La Liga Santanders",
        rank: 6,
        club: "Real Sociedad",
        matchPlayed: 38,
        win: 17,
        draw: 11,
        lost: 10,
        goalsFor: 40,
        goalsAgainst: 37,
        goalsDiff: 3,
        point: 62,
    },
    {
        league: "La Liga Santanders",
        rank: 7,
        club: "Villareal",
        matchPlayed: 38,
        win: 16,
        draw: 11,
        lost: 11,
        goalsFor: 63,
        goalsAgainst: 37,
        goalsDiff: 26,
        point: 59,
    },
    {
        league: "La Liga Santanders",
        rank: 8,
        club: "Athletic Bilbao",
        matchPlayed: 38,
        win: 14,
        draw: 13,
        lost: 11,
        goalsFor: 43,
        goalsAgainst: 36,
        goalsDiff: 7,
        point: 55,
    },
    {
        league: "La Liga Santanders",
        rank: 9,
        club: "Valencia",
        matchPlayed: 38,
        win: 11,
        draw: 15,
        lost: 12,
        goalsFor: 48,
        goalsAgainst: 53,
        goalsDiff: -5,
        point: 48,
    },
    {
        league: "La Liga Santanders",
        rank: 10,
        club: "CA Osasuna",
        matchPlayed: 38,
        win: 12,
        draw: 11,
        lost: 15,
        goalsFor: 37,
        goalsAgainst: 51,
        goalsDiff: -14,
        point: 47,
    },
    {
        league: "La Liga Santanders",
        rank: 11,
        club: "Celta Vigo",
        matchPlayed: 38,
        win: 12,
        draw: 10,
        lost: 16,
        goalsFor: 43,
        goalsAgainst: 63,
        goalsDiff: 0,
        point: 46,
    },
    {
        league: "La Liga Santanders",
        rank: 12,
        club: "Rayo Vallecano",
        matchPlayed: 38,
        win: 11,
        draw: 9,
        lost: 18,
        goalsFor: 39,
        goalsAgainst: 50,
        goalsDiff: -11,
        point: 42,
    },
    {
        league: "La Liga Santanders",
        rank: 13,
        club: "Elche",
        matchPlayed: 38,
        win: 11,
        draw: 9,
        lost: 18,
        goalsFor: 40,
        goalsAgainst: 52,
        goalsDiff: -12,
        point: 42,
    },
    {
        league: "La Liga Santanders",
        rank: 14,
        club: "RCD Espanyol",
        matchPlayed: 38,
        win: 10,
        draw: 12,
        lost: 16,
        goalsFor: 40,
        goalsAgainst: 53,
        goalsDiff: -13,
        point: 42,
    },
    {
        league: "La Liga Santanders",
        rank: 15,
        club: "Getafe",
        matchPlayed: 38,
        win: 8,
        draw: 15,
        lost: 15,
        goalsFor: 33,
        goalsAgainst: 41,
        goalsDiff: -8,
        point: 39,
    },
    {
        league: "La Liga Santanders",
        rank: 16,
        club: "Mallorca",
        matchPlayed: 38,
        win: 10,
        draw: 9,
        lost: 19,
        goalsFor: 36,
        goalsAgainst: 63,
        goalsDiff: -27,
        point: 39,
    },
    {
        league: "La Liga Santanders",
        rank: 17,
        club: "Cadiz",
        matchPlayed: 38,
        win: 8,
        draw: 15,
        lost: 15,
        goalsFor: 35,
        goalsAgainst: 51,
        goalsDiff: -16,
        point: 39,
    },
    {
        league: "La Liga Santanders",
        rank: 18,
        club: "Granada",
        matchPlayed: 38,
        win: 8,
        draw: 14,
        lost: 16,
        goalsFor: 44,
        goalsAgainst: 61,
        goalsDiff: -17,
        point: 38,
    },
    {
        league: "La Liga Santanders",
        rank: 19,
        club: "Levante",
        matchPlayed: 38,
        win: 8,
        draw: 11,
        lost: 19,
        goalsFor: 51,
        goalsAgainst: 76,
        goalsDiff: -25,
        point: 35,
    },
    {
        league: "La Liga Santanders",
        rank: 20,
        club: "Alaves",
        matchPlayed: 38,
        win: 8,
        draw: 7,
        lost: 23,
        goalsFor: 31,
        goalsAgainst: 65,
        goalsDiff: -34,
        point: 31,
    },
    {
        league: "Serie A",
        rank: 1,
        club: "AC Milan",
        matchPlayed: 38,
        win: 26,
        draw: 8,
        lost: 4,
        goalsFor: 69,
        goalsAgainst: 31,
        goalsDiff: 38,
        point: 86,
    },
    {
        league: "Serie A",
        rank: 2,
        club: "Inter Milan",
        matchPlayed: 38,
        win: 25,
        draw: 9,
        lost: 4,
        goalsFor: 84,
        goalsAgainst: 32,
        goalsDiff: 52,
        point: 84,
    },
    {
        league: "Serie A",
        rank: 3,
        club: "Napoli",
        matchPlayed: 38,
        win: 24,
        draw: 7,
        lost: 7,
        goalsFor: 74,
        goalsAgainst: 31,
        goalsDiff: 43,
        point: 79,
    },
    {
        league: "Serie A",
        rank: 4,
        club: "Juventus",
        matchPlayed: 38,
        win: 20,
        draw: 10,
        lost: 8,
        goalsFor: 57,
        goalsAgainst: 37,
        goalsDiff: 20,
        point: 70,
    },
    {
        league: "Serie A",
        rank: 5,
        club: "Lazio",
        matchPlayed: 38,
        win: 18,
        draw: 10,
        lost: 10,
        goalsFor: 77,
        goalsAgainst: 58,
        goalsDiff: 19,
        point: 64,
    },
    {
        league: "Serie A",
        rank: 6,
        club: "AS Roma",
        matchPlayed: 38,
        win: 18,
        draw: 9,
        lost: 11,
        goalsFor: 59,
        goalsAgainst: 43,
        goalsDiff: 16,
        point: 63,
    },
    {
        league: "Serie A",
        rank: 7,
        club: "Fiorentina",
        matchPlayed: 38,
        win: 19,
        draw: 5,
        lost: 14,
        goalsFor: 59,
        goalsAgainst: 51,
        goalsDiff: 8,
        point: 62,
    },
    {
        league: "Serie A",
        rank: 8,
        club: "Atalanta",
        matchPlayed: 38,
        win: 16,
        draw: 11,
        lost: 11,
        goalsFor: 65,
        goalsAgainst: 48,
        goalsDiff: 17,
        point: 59,
    },
    {
        league: "Serie A",
        rank: 9,
        club: "Verona",
        matchPlayed: 38,
        win: 14,
        draw: 11,
        lost: 13,
        goalsFor: 65,
        goalsAgainst: 59,
        goalsDiff: 6,
        point: 53,
    },
    {
        league: "Serie A",
        rank: 10,
        club: "Torino",
        matchPlayed: 38,
        win: 13,
        draw: 11,
        lost: 14,
        goalsFor: 46,
        goalsAgainst: 41,
        goalsDiff: 5,
        point: 50,
    },
    {
        league: "Serie A",
        rank: 11,
        club: "Sassuolo",
        matchPlayed: 38,
        win: 13,
        draw: 11,
        lost: 14,
        goalsFor: 66,
        goalsAgainst: 64,
        goalsDiff: -2,
        point: 50,
    },
    {
        league: "Serie A",
        rank: 12,
        club: "Udinese",
        matchPlayed: 38,
        win: 11,
        draw: 14,
        lost: 13,
        goalsFor: 61,
        goalsAgainst: 58,
        goalsDiff: 3,
        point: 47,
    },
    {
        league: "Serie A",
        rank: 13,
        club: "Bologna",
        matchPlayed: 38,
        win: 12,
        draw: 10,
        lost: 16,
        goalsFor: 44,
        goalsAgainst: 55,
        goalsDiff: -11,
        point: 46,
    },
    {
        league: "Serie A",
        rank: 14,
        club: "Empoli",
        matchPlayed: 38,
        win: 10,
        draw: 11,
        lost: 17,
        goalsFor: 50,
        goalsAgainst: 70,
        goalsDiff: -20,
        point: 41,
    },
    {
        league: "Serie A",
        rank: 15,
        club: "Sampdoria",
        matchPlayed: 38,
        win: 10,
        draw: 6,
        lost: 22,
        goalsFor: 46,
        goalsAgainst: 63,
        goalsDiff: -17,
        point: 36,
    },
    {
        league: "Serie A",
        rank: 16,
        club: "Spezia",
        matchPlayed: 38,
        win: 10,
        draw: 6,
        lost: 22,
        goalsFor: 41,
        goalsAgainst: 71,
        goalsDiff: -30,
        point: 36,
    },
    {
        league: "Serie A",
        rank: 17,
        club: "Salernitana",
        matchPlayed: 38,
        win: 7,
        draw: 10,
        lost: 21,
        goalsFor: 33,
        goalsAgainst: 78,
        goalsDiff: -45,
        point: 31,
    },
    {
        league: "Serie A",
        rank: 18,
        club: "Cagliari",
        matchPlayed: 38,
        win: 6,
        draw: 12,
        lost: 20,
        goalsFor: 34,
        goalsAgainst: 68,
        goalsDiff: -34,
        point: 30,
    },
    {
        league: "Serie A",
        rank: 19,
        club: "Genoa",
        matchPlayed: 38,
        win: 4,
        draw: 16,
        lost: 18,
        goalsFor: 27,
        goalsAgainst: 60,
        goalsDiff: -33,
        point: 28,
    },
    {
        league: "Serie A",
        rank: 20,
        club: "Venezia",
        matchPlayed: 38,
        win: 6,
        draw: 9,
        lost: 23,
        goalsFor: 34,
        goalsAgainst: 69,
        goalsDiff: -35,
        point: 27,
    },
    {
        league: "Bundesliga",
        rank: 1,
        club: "Bayern Munich",
        matchPlayed: 34,
        win: 24,
        draw: 5,
        lost: 5,
        goalsFor: 97,
        goalsAgainst: 37,
        goalsDiff: 60,
        point: 77,
    },
    {
        league: "Bundesliga",
        rank: 2,
        club: "Borussia Dortmund",
        matchPlayed: 34,
        win: 22,
        draw: 3,
        lost: 9,
        goalsFor: 85,
        goalsAgainst: 52,
        goalsDiff: 33,
        point: 69,
    },
    {
        league: "Bundesliga",
        rank: 3,
        club: "Bayer Leverkusen",
        matchPlayed: 34,
        win: 19,
        draw: 7,
        lost: 8,
        goalsFor: 80,
        goalsAgainst: 47,
        goalsDiff: 33,
        point: 64,
    },
    {
        league: "Bundesliga",
        rank: 4,
        club: "RB Leipzig",
        matchPlayed: 34,
        win: 17,
        draw: 7,
        lost: 10,
        goalsFor: 72,
        goalsAgainst: 37,
        goalsDiff: 35,
        point: 58,
    },
    {
        league: "Bundesliga",
        rank: 5,
        club: "Union Berlin",
        matchPlayed: 34,
        win: 16,
        draw: 9,
        lost: 9,
        goalsFor: 50,
        goalsAgainst: 44,
        goalsDiff: 6,
        point: 57,
    },
    {
        league: "Bundesliga",
        rank: 6,
        club: "SC Freiburg",
        matchPlayed: 34,
        win: 15,
        draw: 10,
        lost: 9,
        goalsFor: 58,
        goalsAgainst: 46,
        goalsDiff: 12,
        point: 55,
    },
    {
        league: "Bundesliga",
        rank: 7,
        club: "Koln",
        matchPlayed: 34,
        win: 14,
        draw: 10,
        lost: 10,
        goalsFor: 52,
        goalsAgainst: 49,
        goalsDiff: 3,
        point: 52,
    },
    {
        league: "Bundesliga",
        rank: 8,
        club: "Mainz 05",
        matchPlayed: 34,
        win: 13,
        draw: 7,
        lost: 14,
        goalsFor: 58,
        goalsAgainst: 60,
        goalsDiff: -2,
        point: 46,
    },
    {
        league: "Bundesliga",
        rank: 9,
        club: "Hoffenheim",
        matchPlayed: 34,
        win: 13,
        draw: 7,
        lost: 14,
        goalsFor: 58,
        goalsAgainst: 60,
        goalsDiff: -2,
        point: 46,
    },
    {
        league: "Bundesliga",
        rank: 10,
        club: "Borussia Monchengladbach",
        matchPlayed: 34,
        win: 12,
        draw: 9,
        lost: 13,
        goalsFor: 54,
        goalsAgainst: 61,
        goalsDiff: -7,
        point: 45,
    },
    {
        league: "Bundesliga",
        rank: 11,
        club: "Eintracht Frankfurt",
        matchPlayed: 34,
        win: 10,
        draw: 12,
        lost: 12,
        goalsFor: 45,
        goalsAgainst: 49,
        goalsDiff: -4,
        point: 42,
    },
    {
        league: "Bundesliga",
        rank: 12,
        club: "Wolfsburg",
        matchPlayed: 34,
        win: 12,
        draw: 6,
        lost: 16,
        goalsFor: 43,
        goalsAgainst: 54,
        goalsDiff: -11,
        point: 42,
    },
    {
        league: "Bundesliga",
        rank: 13,
        club: "VfL Bochum",
        matchPlayed: 34,
        win: 12,
        draw: 6,
        lost: 16,
        goalsFor: 38,
        goalsAgainst: 52,
        goalsDiff: -11,
        point: 42,
    },
    {
        league: "Bundesliga",
        rank: 14,
        club: "Augsburg",
        matchPlayed: 34,
        win: 10,
        draw: 8,
        lost: 16,
        goalsFor: 39,
        goalsAgainst: 56,
        goalsDiff: -17,
        point: 38,
    },
    {
        league: "Bundesliga",
        rank: 15,
        club: "VfB Stuttgart",
        matchPlayed: 34,
        win: 7,
        draw: 12,
        lost: 15,
        goalsFor: 41,
        goalsAgainst: 59,
        goalsDiff: -18,
        point: 33,
    },
    {
        league: "Bundesliga",
        rank: 16,
        club: "Hertha Berlin",
        matchPlayed: 34,
        win: 7,
        draw: 12,
        lost: 15,
        goalsFor: 41,
        goalsAgainst: 59,
        goalsDiff: -18,
        point: 33,
    },
    {
        league: "Bundesliga",
        rank: 17,
        club: "Arminia",
        matchPlayed: 34,
        win: 5,
        draw: 13,
        lost: 16,
        goalsFor: 27,
        goalsAgainst: 53,
        goalsDiff: -26,
        point: 28,
    },
    {
        league: "Bundesliga",
        rank: 18,
        club: "Furth",
        matchPlayed: 34,
        win: 3,
        draw: 9,
        lost: 22,
        goalsFor: 28,
        goalsAgainst: 82,
        goalsDiff: -54,
        point: 18,
    },
    {
        league: "Ligue 1",
        rank: 1,
        club: "Paris Saint-Germain",
        matchPlayed: 38,
        win: 26,
        draw: 8,
        lost: 4,
        goalsFor: 90,
        goalsAgainst: 36,
        goalsDiff: 54,
        point: 86,
    },
    {
        league: "Ligue 1",
        rank: 2,
        club: "Marseille",
        matchPlayed: 38,
        win: 21,
        draw: 8,
        lost: 9,
        goalsFor: 63,
        goalsAgainst: 38,
        goalsDiff: 25,
        point: 71,
    },
    {
        league: "Ligue 1",
        rank: 3,
        club: "AS Monaco",
        matchPlayed: 38,
        win: 20,
        draw: 9,
        lost: 9,
        goalsFor: 65,
        goalsAgainst: 40,
        goalsDiff: 25,
        point: 69,
    },
    {
        league: "Ligue 1",
        rank: 4,
        club: "Rennes",
        matchPlayed: 38,
        win: 20,
        draw: 6,
        lost: 12,
        goalsFor: 82,
        goalsAgainst: 40,
        goalsDiff: 42,
        point: 66,
    },
    {
        league: "Ligue 1",
        rank: 5,
        club: "Nice",
        matchPlayed: 38,
        win: 20,
        draw: 7,
        lost: 11,
        goalsFor: 52,
        goalsAgainst: 36,
        goalsDiff: 16,
        point: 66,
    },
    {
        league: "Ligue 1",
        rank: 6,
        club: "Strasbourg",
        matchPlayed: 38,
        win: 17,
        draw: 12,
        lost: 9,
        goalsFor: 60,
        goalsAgainst: 43,
        goalsDiff: 17,
        point: 63,
    },
    {
        league: "Ligue 1",
        rank: 7,
        club: "Lens",
        matchPlayed: 38,
        win: 17,
        draw: 11,
        lost: 10,
        goalsFor: 62,
        goalsAgainst: 48,
        goalsDiff: 14,
        point: 62,
    },
    {
        league: "Ligue 1",
        rank: 8,
        club: "Lyon",
        matchPlayed: 38,
        win: 17,
        draw: 11,
        lost: 10,
        goalsFor: 66,
        goalsAgainst: 51,
        goalsDiff: 15,
        point: 61,
    },
    {
        league: "Ligue 1",
        rank: 9,
        club: "Nantes",
        matchPlayed: 38,
        win: 15,
        draw: 10,
        lost: 13,
        goalsFor: 55,
        goalsAgainst: 48,
        goalsDiff: 7,
        point: 55,
    },
    {
        league: "Ligue 1",
        rank: 10,
        club: "LOSC Lille",
        matchPlayed: 38,
        win: 14,
        draw: 13,
        lost: 11,
        goalsFor: 48,
        goalsAgainst: 48,
        goalsDiff: 0,
        point: 55,
    },
    {
        league: "Ligue 1",
        rank: 11,
        club: "Brest",
        matchPlayed: 38,
        win: 13,
        draw: 9,
        lost: 16,
        goalsFor: 49,
        goalsAgainst: 6257,
        goalsDiff: -8,
        point: 48,
    },
    {
        league: "Ligue 1",
        rank: 12,
        club: "Stade de Reims",
        matchPlayed: 38,
        win: 11,
        draw: 13,
        lost: 14,
        goalsFor: 43,
        goalsAgainst: 44,
        goalsDiff: -1,
        point: 46,
    },
    {
        league: "Ligue 1",
        rank: 13,
        club: "Montpellier",
        matchPlayed: 38,
        win: 12,
        draw: 7,
        lost: 19,
        goalsFor: 49,
        goalsAgainst: 61,
        goalsDiff: -12,
        point: 43,
    },
    {
        league: "Ligue 1",
        rank: 14,
        club: "Angers",
        matchPlayed: 38,
        win: 10,
        draw: 11,
        lost: 17,
        goalsFor: 44,
        goalsAgainst: 55,
        goalsDiff: -11,
        point: 41,
    },
    {
        league: "Ligue 1",
        rank: 15,
        club: "Troyes",
        matchPlayed: 38,
        win: 9,
        draw: 11,
        lost: 18,
        goalsFor: 37,
        goalsAgainst: 53,
        goalsDiff: -16,
        point: 38,
    },
    {
        league: "Ligue 1",
        rank: 16,
        club: "Lorient",
        matchPlayed: 38,
        win: 8,
        draw: 12,
        lost: 18,
        goalsFor: 35,
        goalsAgainst: 63,
        goalsDiff: -28,
        point: 36,
    },
    {
        league: "Ligue 1",
        rank: 17,
        club: "Clermont Foot",
        matchPlayed: 38,
        win: 9,
        draw: 9,
        lost: 20,
        goalsFor: 38,
        goalsAgainst: 69,
        goalsDiff: -31,
        point: 36,
    },
    {
        league: "Ligue 1",
        rank: 18,
        club: "Saint-Etienne",
        matchPlayed: 38,
        win: 7,
        draw: 11,
        lost: 20,
        goalsFor: 42,
        goalsAgainst: 77,
        goalsDiff: -35,
        point: 32,
    },
    {
        league: "Ligue 1",
        rank: 19,
        club: "Metz",
        matchPlayed: 38,
        win: 6,
        draw: 13,
        lost: 19,
        goalsFor: 35,
        goalsAgainst: 69,
        goalsDiff: -34,
        point: 31,
    },
    {
        league: "Ligue 1",
        rank: 20,
        club: "Bordeaux",
        matchPlayed: 38,
        win: 6,
        draw: 13,
        lost: 19,
        goalsFor: 52,
        goalsAgainst: 91,
        goalsDiff: -39,
        point: 31,
    },
];

export const getStandingsPost = () => {
    var posts = standingsData;
    var myPromise = new Promise((resolve, reject) => {
        resolve(posts);
    });
    return myPromise;
};

export const getListStandingsByLeague = (league) => {
    var post = standingsData.filter(x => x.league == league);

    var myPromise = new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve(post);
        }, 1000)
    });
    return myPromise;
}